version: '3.8'
networks:
  social-app:
    driver: bridge
services:
  db:
    container_name: db_container
    image: amd64/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: "true"
      # MYSQL_DATABASE: test_db
      # MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: me
      MYSQL_PASSWORD: secret
      # MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: my_db
    volumes:
      - .db-init:/docker-entrypoint-initdb.d
      # - db:/var/lib/mysql
    networks:
      - social-app
  api:
    container_name: social_app
    networks:
      - social-app
    depends_on:
      - db
    restart: unless-stopped
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 5; done; node server.js'
    build:
      context: ./
    volumes:
      - '.:/app'
    ports:
      - '8080:8080'
      - '9229:9229'
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    stdin_open: true
    tty: true
volumes:
  db: