openapi: 3.0.0
info:
  title: 1-social-network
  version: 1.0.0
  license:
    name: ISC
  description: |-
    Specification JSONs: [v2](/api-spec/v2), [v3](/api-spec/v3).

    First hometask for OTUS Highload architect course
paths:
  /:
    get:
      summary: /
      responses:
        '302':
          description: Found
          content:
            text/plain:
              schema:
                type: string
                example: Found. Redirecting to /me
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /me:
    get:
      summary: /me
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: '<head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Dashboard | Social App</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/><link rel="stylesheet" href="main.css"/></head><body><nav class="navbar navbar-expand-lg navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="/me">Social App</a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navbarsExample07"><ul class="navbar-nav mr-auto"><li class="nav-item active"><a class="nav-link" href="/me">Me</a></li><li class="nav-item"><a class="nav-link" href="/pages">Pages</a></li><li class="nav-item"><a class="nav-link" id="logout" href="">Logout</a></li></ul><form class="form-inline my-2 my-md-0"><input class="form-control" type="text" placeholder="Search" aria-label="Search"/></form></div></div></nav><div class="container"><div class="card"><svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Image cap" preserveaspectratio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"></rect><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg><div class="card-body"><h5 class="card-title">Kirill Romanov</h5><p>Возраст: 26</p><p>Пол: M</p><p>Город: NN</p><p class="card-text">Интересы: games</p><a class="btn btn-primary" href="#">Go somewhere</a></div></div></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="main_layout_scripts.js"> </script></body>'
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /login:
    get:
      summary: /login
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: '<head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Sign In | Social App</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/><link rel="stylesheet" href="main.css"/></head><body><section class="vh-100"><div class="container py-5 h-100"><div class="row d-flex align-items-center justify-content-center h-100"><div class="col-md-8 col-lg-7 col-xl-6"><img class="img-fluid" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg" alt="Phone image"/></div><div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1"><h2>Welcome to the social app!</h2><form id="login"><!-- Email input--><div class="form-outline mb-4"><input class="form-control form-control-lg" id="form1Example13" type="text"/><label class="form-label" for="form1Example13">Username</label></div><!-- Password input--><div class="form-outline mb-4"><input class="form-control form-control-lg" id="form1Example23" type="password"/><label class="form-label" for="form1Example23">Password</label></div><div class="d-flex justify-content-around align-items-center mb-4"><!-- Checkbox--><div class="form-check"><input class="form-check-input" id="form1Example3" type="checkbox" value="" checked=""/><label class="form-check-label" for="form1Example3"> Remember me </label></div><a href="/register">Forgot password?</a></div><!-- Submit button--><button class="btn btn-primary btn-lg btn-block" type="submit">Sign In</button><button class="btn btn-outline-primary" id="signup" type="button">Sign Up</button></form><p id="error" style="display: block; color: red;">Login Failed! Try again.</p></div></div></div></section><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="login.js"></script></body>'
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /register:
    get:
      summary: /register
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: '<head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Sign Up | Social App</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/><link rel="stylesheet" href="main.css"/></head><body><section class="vh-100" style="background-color: #eee;"><div class="container h-100"><div class="row d-flex justify-content-center align-items-center h-100"><div class="col-lg-12 col-xl-11"><div class="card text-black" style="border-radius: 25px;"><div class="card-body p-md-5"><div class="row justify-content-center"><div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1"><p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p><form class="mx-1 mx-md-4" id="signup"><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-user fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signUpName" name="firstName" required="" type="text"/><label class="form-label" for="signUpName">Имя</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-user fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signUpLastName" name="lastName" required="" type="text"/><label class="form-label" for="signUpLastName">Фамилия</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-user fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signUpAge" name="age" required="" type="number" min="1" max="100"/><label class="form-label" for="signUpAge">Возраст</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-user fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><select class="form-select" required="" name="gender"><option selected="" disabled=""></option><option value="male">мужской</option><option value="female">женский</option></select><label class="form-label" for="signUpGender">Пол</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-envelope fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><textarea class="form-control" id="signUpInterests" name="interests" placeholder="Опишите Ваши интересы" required=""></textarea><label for="signUpInterests">Интересы</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-user fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signUpCity" name="city" required="" type="text"/><label class="form-label" for="signUpCity">Город</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-envelope fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signUpUsername" name="username" required="" type="text"/><label class="form-label" for="signUpUsername">Username</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-lock fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signupPassword1" name="pass1" required="" type="password"/><label class="form-label" for="signupPassword1">Пароль</label></div></div><div class="d-flex flex-row align-items-center mb-4"><i class="fas fa-key fa-lg me-3 fa-fw"></i><div class="form-outline flex-fill mb-0"><input class="form-control" id="signupPassword2" name="pass2" required="" type="password"/><label class="form-label" for="signupPassword2">Пароль еще раз</label></div></div><div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4"><button class="btn btn-primary btn-lg" type="submit">Submit</button></div><p id="error">произошла ошибка: </p></form></div><div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2"><img class="img-fluid" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp" alt="Sample image"/></div></div></div></div></div></div></div></section><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="register.js"> </script></body>'
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /pages:
    get:
      summary: /pages
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: string
                example: <head><meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>Pages | Social App</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/><link rel="stylesheet" href="main.css"/></head><body><nav class="navbar navbar-expand-lg navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="/me">Social App</a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="navbarsExample07"><ul class="navbar-nav mr-auto"><li class="nav-item active"><a class="nav-link" href="/me">Me</a></li><li class="nav-item"><a class="nav-link" href="/pages">Pages</a></li><li class="nav-item"><a class="nav-link" id="logout" href="">Logout</a></li></ul><form class="form-inline my-2 my-md-0"><input class="form-control" type="text" placeholder="Search" aria-label="Search"/></form></div></div></nav><div class="container"></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script><script src="main_layout_scripts.js"> </script></body>
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /api/signin:
    post:
      summary: /api/signin
      responses:
        '302':
          description: Found
          content:
            text/plain:
              schema:
                type: string
                example: Found. Redirecting to /me
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /api/signup:
    post:
      summary: /api/signup
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  newUserId:
                    type: number
                    example: 1
                  message:
                    type: string
                    example: User created
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /api/me/page:
    get:
      summary: /api/me/page
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    user:
                      type: object
                      properties:
                        uid:
                          type: number
                        userName:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        age:
                          type: number
                        gender:
                          type: string
                        city:
                          type: string
                        interests:
                          type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /api/pages:
    get:
      summary: /api/pages
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    user:
                      type: object
                      properties:
                        uid:
                          type: number
                        userName:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        age:
                          type: number
                        gender:
                          type: string
                        city:
                          type: string
                        interests:
                          type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
  /api/pages/{pageId}:
    get:
      summary: /api/pages/{pageId}
      parameters:
        - name: pageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    title:
                      type: string
                    user:
                      type: object
                      properties:
                        uid:
                          type: number
                        userName:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        age:
                          type: number
                        gender:
                          type: string
                        city:
                          type: string
                        interests:
                          type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4eor0fjc7qlm25a9h45
        tag: $latest
        service_account_id: ajef225h7o2qmd797b3a
      tags: []
tags: []
